// Symbols
const OPENING_PARENTHESIS = '(';
const CLOSING_PARENTHESIS = ')';
const OPENING_CURLY_BRACKET= '{';
const CLOSING_CURLY_BRACKET= '}';
const OPENING_SQUARE_BRACKET= '[';
const CLOSING_SQUARE_BRACKET= ']';
const SEMICOLON=';';
const DOLLAR = '$';
const AMPERSAND = '&';

// Types
const SHAPE_TYPE = 'shape'
const COMMENT_TYPE = 'comment';
const VALUESET_TYPE = 'valueSet';
const PREFIXED_IRI = 'string-2';
const IRI = 'variable-3';

// Keywords
const AND_KEYWORD = 'and';
const OR_KEYWORD = 'or';


module.exports ={
    OPENING_PARENTHESIS:OPENING_PARENTHESIS,
    CLOSING_PARENTHESIS:CLOSING_PARENTHESIS,
    OPENING_CURLY_BRACKET:OPENING_CURLY_BRACKET,
    CLOSING_CURLY_BRACKET:CLOSING_CURLY_BRACKET,
    OPENING_SQUARE_BRACKET:OPENING_SQUARE_BRACKET,
    CLOSING_SQUARE_BRACKET:CLOSING_SQUARE_BRACKET,
    SEMICOLON:SEMICOLON,
    SHAPE_TYPE:SHAPE_TYPE,
    COMMENT_TYPE:COMMENT_TYPE,
    VALUESET_TYPE:VALUESET_TYPE,
    PREFIXED_IRI:PREFIXED_IRI,
    IRI:IRI,
    AND_KEYWORD:AND_KEYWORD,
    OR_KEYWORD:OR_KEYWORD
}